YUI_VERSION=3.18.1
YUI_FILES=\
	yui/yui-min.js \
	oop/oop-min.js \
	event-custom-base/event-custom-base-min.js \
	event-custom-complex/event-custom-complex-min.js \
	event-base/event-base-min.js \
	event-touch/event-touch-min.js \
	dom-core/dom-core-min.js \
	dom-base/dom-base-min.js \
	selector-native/selector-native-min.js \
	selector/selector-min.js \
	node-core/node-core-min.js \
	async-queue/async-queue-min.js \
	dom-style/dom-style-min.js \
	node-base/node-base-min.js \
	event-delegate/event-delegate-min.js \
	node-event-delegate/node-event-delegate-min.js \
	pluginhost-base/pluginhost-base-min.js \
	pluginhost-config/pluginhost-config-min.js \
	node-pluginhost/node-pluginhost-min.js \
	dom-screen/dom-screen-min.js \
	node-screen/node-screen-min.js \
	node-style/node-style-min.js \
	attribute-core/attribute-core-min.js \
	attribute-observable/attribute-observable-min.js \
	attribute-extras/attribute-extras-min.js \
	attribute-base/attribute-base-min.js \
	base-core/base-core-min.js \
	base-observable/base-observable-min.js \
	base-base/base-base-min.js \
	base-pluginhost/base-pluginhost-min.js \
	base-build/base-build-min.js \
	yui-throttle/yui-throttle-min.js \
	classnamemanager/classnamemanager-min.js \
	dd-ddm-base/dd-ddm-base-min.js \
	event-synthetic/event-synthetic-min.js \
	event-resize/event-resize-min.js \
	dd-ddm/dd-ddm-min.js \
	dd-ddm-drop/dd-ddm-drop-min.js \
	selector-css2/selector-css2-min.js \
	dd-drag/dd-drag-min.js \
	dd-gestures/dd-gestures-min.js \
	dd-proxy/dd-proxy-min.js \
	dd-constrain/dd-constrain-min.js \
	dd-drop/dd-drop-min.js \
	dd-scroll/dd-scroll-min.js \
	dd-drop-plugin/dd-drop-plugin-min.js \
	event-mouseenter/event-mouseenter-min.js \
	dd-delegate/dd-delegate-min.js \
	cookie/cookie-min.js \
	array-extras/array-extras-min.js \
	color-base/color-base-min.js \
	anim-base/anim-base-min.js \
	anim-easing/anim-easing-min.js \
	event-flick/event-flick-min.js \
	event-move/event-move-min.js \
	attribute-complex/attribute-complex-min.js \
	event-focus/event-focus-min.js \
	widget-base/widget-base-min.js \
	widget-htmlparser/widget-htmlparser-min.js \
	widget-skin/widget-skin-min.js \
	widget-uievents/widget-uievents-min.js \
	arraylist/arraylist-min.js \
	widget-parent/widget-parent-min.js \
	widget-child/widget-child-min.js \
	tabview-base/tabview-base-min.js \
	plugin/plugin-min.js \
	event-simulate/event-simulate-min.js \
	gesture-simulate/gesture-simulate-min.js \
	node-event-simulate/node-event-simulate-min.js \
	event-key/event-key-min.js \
	node-focusmanager/node-focusmanager-min.js \
	tabview/tabview-min.js \
