name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK for YUI compressor
      uses: actions/setup-java@v4
      with:
        java-version: '21'  # some LTS version with long support
        distribution: 'temurin'
        architecture: x64

    - name: Download YUI compressor
      run: wget -O ../yuicompressor-2.4.8.jar https://github.com/yui/yuicompressor/releases/download/v2.4.8/yuicompressor-2.4.8.jar

    - name: Build
      run: make YUI_COMPRESSOR=../yuicompressor-2.4.8.jar -j9 final

    - uses: actions/upload-artifact@v4
      with:
        name: pasians-site
        path: final

    - run: mkdir staging-dist

    - run: cp -ra final staging-dist/cekej

    - name: Publish to Cloudflare Pages
      uses: cloudflare/pages-action@v1
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: 991b370147d5a485555e591f6f087b22
        projectName: trpelivost
        directory: staging-dist
